package com.onedoorway.project.model;

public enum LookupType {
    INCIDENT_CATEGORY,
    INCIDENT_CLASSIFICATION,
    INCIDENT_TYPE,
    INCIDENT_ENVIRONMENT_FACTOR,
    INCIDENT_HOUSE_ASSET_FACTOR,
    INCIDENT_PERSON_FACTOR,
    REPORTS,
    NIGHTLY_TASKS,
    MISCELLANEOUS_NOTES,
    CASE_NOTES
}
